### ISSUE TITLE
Not really an issue: Add former XNA TTF redistributable as Open Source

### ISSUE THREAD

**Issue by Mephisztoe** [Microsoft/fonts#4]
Game developers need to use fonts in the games. Especially indie developers are constantly looking for high quality open source fonts. Is it possible to add the former XNA redistributable fonts that you can still download here: http://bit.ly/tmg-fontpack to this list of Open Source fonts?

**Comment by aaronbell** [comment]
Thanks for the comment! While it would definitely be great to put all of these usable fonts in the same place, there's a definite difference between redistributable and Open Source. Do you have a contact for who put this online originally?

**Comment by Mephisztoe** [comment]
You're absolutely right! There's an important difference. The redistributable fonts are actually OpenType Fonts created by the Ascender Corporation and licensed by Microsoft to be included in XNA Game Studio, so that they can be freely used in XNA games. However... XNA is dead and Ascender has been aquired by Monotype Imaging in the meantime. So it actually looks like it would be not at all possible to resolve this topic so that these fonts can be published Open Source eventually. :(

More on this here:
http://xbox.create.msdn.com/en-US/education/catalog/utility/font_pack

**Comment by aaronbell** [comment]
Thanks for the info! We don't have an issue with the fonts being distributed as part of the XNA Game Studio, but don't have plans to Open Source them at this time. Sorry!
