### ISSUE TITLE
Font binaries are corrupt due to line feed conversion

### ISSUE THREAD

**Issue by codeman38** [Microsoft/fonts#5]
Somehow, it looks like all of the font files committed to this repo had line feed conversion applied, so that all 0x0D 0x0A byte pairs were converted to 0x0A upon commit.

Needless to say, this makes the fonts completely unusable.

As a checksum of sorts, the file sizes should match those in the Winstrap repository:

Font | Bytes
---- | ----
selawk.ttf | 44224
selawkb.ttf | 44068
selawkl.ttf | 44232
selawksb.ttf | 44192
selawksl.ttf | 44260
winjs-symbols.ttf | 47488

**Edited to add:** This seems to be due to the .gitattributes file, which defines a default conversion of `* text eol=lf`. This should probably have the following appended, to ensure that the non-SVG font files don't get mangled:
```
*.eot binary
*.ttf binary
*.woff binary
*.woff2 binary
```

**Comment by aaronbell** [comment]
Oh! That's weird. Thanks for catching this! I've updated all the font files and the .gitattributes to avoid this issue in the future. I've temporarily removed some of the webfont files until we can get them remade. 

Thanks!

**Comment by codeman38** [comment]
It looks like the fonts are still corrupted. It may be necessary to do one commit removing the fonts, then another re-adding them.

**Comment by rachelnizh** [comment]
Thanks for the catch @codeman38. Sorry about that everyone. I was trying to be helpful by taking care of line endings for everyone and corrupted the non-SVG files in the process. *Cue sad trombone music.* I'll submit a PR with fresh files.

**Comment by aaronbell** [comment]
I've resubmitted the fonts that I previously uploaded as well. Apparently they needed to be removed first.
