### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by davelab6** [Microsoft/fonts#8]
I suggest adding the source files and build scripts for each project :)

**Comment by adrientetar** [comment]
Also removing binaries from repository and tag releases instead.

**Comment by davelab6** [comment]
@adrientetar are there any libre font git repos you think are exemplary?

**Comment by adrientetar** [comment]
None of mine are public, but https://github.com/adobe-fonts/source-sans-pro is pretty good.

**Comment by aaronbell** [comment]
Thanks for the feedback! I think there is value in keeping the binaries here as Dave pointed out in the [https://github.com/Microsoft/fonts/issues/7](other issue), this will act as an upstream source for others to use the Binary font files, as well as a source for the files. 

I'm putting the source files through review :)

**Comment by davelab6** [comment]
(Your link got the markdown syntax for anchor and url mixed up, feel free to delete this comment if fixed up)

**Comment by davelab6** [comment]
I'm not sure having the binaries in this repo is ideal; google/fonts has binaries, but its repo made specifically for ingesting the fonts into the GF API. 

Adrien is suggesting to add sources and remove the binaries and use the https://github.com/Microsoft/fonts/releases system to attach the binaries to marked points in the sources' development. 

Maybe overcomplicating things, though.

**Comment by adrientetar** [comment]
Yeah it doesn't matter especially given that repo is mainly a storage, but otherwise that's TWIMTBP.

**Comment by adrientetar** [comment]
That was fast, Aaron. Great stuff.

**Comment by aaronbell** [comment]
Got sign off. :)
